// This file is auto-generated by Supabase CLI.
// Run: supabase gen types typescript --linked > src/types/database.ts
// after completing Phase 2 (Supabase setup).

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      // Tables will be populated after Phase 4 schema is applied
      [key: string]: {
        Row: Record<string, unknown>
        Insert: Record<string, unknown>
        Update: Record<string, unknown>
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
